// Profile Store Types
export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_STATISTICS = "SET_PROFILE_STATISTICS";
// Organization Store Types
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const SET_IMPORTED_REPOSITORIES = "SET_IMPORTED_REPOSITORIES";
export const CLEAR_IMPORTED_REPOSITORIES = "CLEAR_IMPORTED_REPOSITORIES";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const CLEAR_ORGANIZATIONS = "CLEAR_ORGANIZATIONS";
export const SET_MINIMAL_ORGANIZATIONS = "SET_MINIMAL_ORGANIZATIONS";

// Repository Store Types
export const SET_REPOSITORY = "SET_REPOSITORY";
export const SET_REPOSITORIES = "SET_REPOSITORIES";
export const CLEAR_REPOSITORIES = "CLEAR_REPOSITORIES";
export const SET_MINIMAL_REPOSITORIES = "SET_MINIMAL_REPOSITORIES";
export const SET_SOLUTION_REPOSITORIES = "SET_SOLUTION_REPOSITORIES";
export const SET_TEMPLATE_REPOSITORIES = "SET_TEMPLATE_REPOSITORIES";
export const SET_CANVAS_COURSES = "SET_CANVAS_COURSES";
export const SET_CANVAS_STUDENTS = "SET_CANVAS_STUDENTS";

// User Store Types
export const SET_USER = "SET_USER";
export const SET_USERS = "SET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
export const SET_MINIMAL_USERS = "SET_MINIMAL_USERS";